"""Add description to servers

Revision ID: e453ebaaa3d0
Revises: ee9ef544852a
Create Date: 2025-05-11 08:56:40.255293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e453ebaaa3d0'
down_revision: Union[str, None] = 'ee9ef544852a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_devices_hostname', table_name='devices')
    op.drop_index('ip_address', table_name='ips')
    op.drop_constraint('fk_ips_updated_by_admins', 'ips', type_='foreignkey')
    op.create_foreign_key(None, 'ips', 'admins', ['updated_by'], ['id'])
    op.add_column('servers', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'description')
    op.drop_constraint(None, 'ips', type_='foreignkey')
    op.create_foreign_key('fk_ips_updated_by_admins', 'ips', 'admins', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_index('ip_address', 'ips', ['ip_address'], unique=True)
    op.create_index('uq_devices_hostname', 'devices', ['hostname'], unique=True)
    # ### end Alembic commands ###
